export enum InterviewEvent {
  INTRO_DONE = "INTRO_DONE",
  START_RECORDING = "START_RECORDING",
  ANSWER_SUBMITTED = "ANSWER_SUBMITTED",
  PROCESSING_DONE = "PROCESSING_DONE",
  FEEDBACK_ACK = "FEEDBACK_ACK",
  CHECKPOINT_ACK = "CHECKPOINT_ACK",
  COMPLETE_INTERVIEW = "COMPLETE_INTERVIEW",
  PAUSE = "PAUSE",
  RESUME = "RESUME",
}
