export enum InterviewState {
  INTRO = "INTRO",
  QUESTION = "QUESTION",
  RECORDING = "RECORDING",
  PROCESSING = "PROCESSING",
  MICRO_FEEDBACK = "MICRO_FEEDBACK",
  CHECKPOINT = "CHECKPOINT",
  COMPLETED = "COMPLETED",
  ERROR = "ERROR",
  PAUSED = "PAUSED",
}
